services:
  admin-back:
    build:
      context: ./admin-back
      dockerfile: Dockerfile
      args:
        GO_VERSION: 1.25.4
    ports:
      - "8080:8080"

  admin-ui:
    build:
      context: ./admin-ui
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://localhost:8080
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080
    depends_on:
      - admin-back
    ports:
      - "3000:3000"
